MineWatch:
  DB_URI: "jdbc:mysql://mysql-hungrycodes.alwaysdata.net:3306/hungrycodes_minewatch?useSSL=false"
  USER: "307217_sandro"
  PASS: "Sandro3345"
  TABLE: "table_joueurs"

SetAccessDataInput:
  onPlayerJoin: true
  onPlayerQuit: true
  onBlockBreak: true
  onBlockPlace: true
  onPlayerDeath: true
  onPlayerRespawn: true
