# Config file for MineWatchPlugin

MineWatch:
  DB_URI: "jdbc:mysql://localhost:3306/database?useSSL=false"
  USER: "root"
  PASS: "root"
  TABLE: "yourtable"

SetAccessDataInput:
  onPlayerJoin: true
  onPlayerQuit: true
  onBlockBreak: true
  onBlockPlace: true
  onPlayerDeath: true
  onPlayerRespawn: true
